### ISSUE TITLE
Symfony rewrite todo list

### ISSUE THREAD

**Issue by kongr45gpen** [kongr45gpen/stev-manager#16]
- [x] Event list
- [ ] Volunteer list
- [ ] Volunteer availability calendar
- [x] Importing schedules
- [ ] Importing volunteers
- [ ] Exporting e-mail addresses
- [ ] Exporting XLSX schedules
- [x] Exporting DOCX data
- [ ] Statistics
- [ ] Better administration interface
- [x] Parsing and storing of JSON data
- [x] Users & Security
  - Login form
- [x] User tokens
- [ ] Support for event categories/types
- [ ] Icons for event types
- [x] Audits
- [ ] Comments
- [ ] LaTeX export
- [ ] PanDoc support for Markdown
- [x] Timestampable models
- [x] Auditable models
- [ ] Sort log entries in reverse
